---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12, 3.13]
    outputs:
      cache-key: ${{ steps.cache-deps.outputs.cache-key }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v1

      - name: Cache uv dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ matrix.python-version }}-${{ hashFiles('requirements.lock') }}

      - name: Install dependencies (locked)
        run: uv pip install -r requirements.lock

  lint:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12, 3.13]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: astral-sh/setup-uv@v1
      - uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ matrix.python-version }}-${{ hashFiles('requirements.lock') }}
      - run: uv pip install pre-commit
      - uses: pre-commit/action@v3.0.1

  ruff:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12, 3.13]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: astral-sh/setup-uv@v1
      - uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ matrix.python-version }}-${{ hashFiles('requirements.lock') }}
      - run: uv pip install ruff
      - run: ruff check Summarizer tests

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12, 3.13]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: astral-sh/setup-uv@v1
      - uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ matrix.python-version }}-${{ hashFiles('requirements.lock') }}
      - run: uv pip install pytest pytest-cov
      - run: pytest --cov=Summarizer tests/

  bandit:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12, 3.13]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: astral-sh/setup-uv@v1
      - uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ matrix.python-version }}-${{ hashFiles('requirements.lock') }}
      - run: uv pip install bandit
      - run: bandit -r Summarizer

  radon:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12, 3.13]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: astral-sh/setup-uv@v1
      - uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ matrix.python-version }}-${{ hashFiles('requirements.lock') }}
      - run: uv pip install radon
      - run: radon cc -s -a Summarizer
